### PR TITLE
Fix the RISC-V target in the README

### PR DESCRIPTION
**Pull request by jessebraham**
Just noticed this one. While using only the `i` extension will likely be fine for simple demos, it's best to include all supported extensions. Hardware-accelerated multiplication/division (`m`) and compressed instructions (`c`) are both pretty useful.

### CODE REVIEW

**Comment by SergioGasquez** [comment]
Do you mind updating also [the installer](https://github.com/esp-rs/rust-build/blob/364387a8bf637e1b2a3ca6b5aeb5fbed2969d927/install-rust-toolchain.sh#L275)?

**Comment by jessebraham** [comment]
Oops missed that one, it's been updated.

**Comment by georgik** [comment]
@SergioGasquez It seems that the change conflicts with the latest merged changes. Could you resolve the conflict?

**Comment by SergioGasquez** [comment]
> Could you resolve the conflict?

Done!

**Pull request merged**
