### PR TITLE
Modernize bash script

### LINKED ISSUE #113: Running ./install-rust-toolchain.sh without args results in error
Running plain `./install-rust-toolchain.sh` currently results in an error:
```
./install-rust-toolchain.sh: line 607: : No such file or directory
```
This is because the `EXPORT_FILE` is used despite being unset.

### PR DESCRIPTION
**Pull request by svenstaro**
This improves a few things about the install script:
- Set strict mode and check that there are no unset variables and fix instances of where that is currently the case
- Use bash builtin conditional characters
- Restructure the export file logic and only make it output to shell if `EXPORT_FILE` is unset

Fixes #113.

### CODE REVIEW

**Comment by svenstaro** [comment]
I think the CI failure isn't caused by this.

**Comment by SergioGasquez** [comment]
Thanks for the contribution! The CI failure is due to: https://github.com/esp-rs/esp-idf-sys/issues/99

**Comment by svenstaro** [comment]
> Thanks for the contribution! The CI failure is due to: [esp-rs/esp-idf-sys#99](https://github.com/esp-rs/esp-idf-sys/issues/99)

Is this blocking this PR?

**Review by SergioGasquez — APPROVED** [review]
LGTM! Thanks again!

**Comment by georgik** [comment]
Thank you @svenstaro for a great improvement of the code. Initial tests seem to be ok. Let's include changes in the new installer for 1.62.1.0, which will also contain several fixes to the compiler.

**Comment by SergioGasquez** [comment]
`set -u` seems to make the installer crash on macos with:
```sh
install-rust-toolchain.sh: line 141: POSITIONAL[@]: unbound variable
```

Using `POSITIONAL=""` in [definition of `POSTIONAL`](https://github.com/esp-rs/rust-build/blob/7738fddb8017bad5359886a715856a730b7012bd/install-rust-toolchain.sh#L49) seems to solve it but I am not sure if there are any implications of this change.

**Pull request merged**
