### PR TITLE
Build/1.64.0.0

### PR DESCRIPTION
**Pull request by georgik**

### CODE REVIEW

**Comment by lynaghk** [comment]
Please don't forget to add https://github.com/esp-rs/rust-build/pull/128/commits/5d9464bc91f8dcb7e761b7f3ebb6e28db12e0f72 to this branch --- I just tried the pre-release (i.e., installing via https://github.com/esp-rs/rust-build/blob/321226ffac0effa649d5e079eb2900a8cf9ba8a3/install-rust-toolchain.sh) and the downloaded toolchain tried to link to openssl:

```
dyld[14004]: Library not loaded: '/opt/homebrew/opt/openssl@3/lib/libssl.3.dylib'
  Referenced from: '/Users/dev/.rustup/toolchains/esp/bin/cargo'
  Reason: tried: '/opt/homebrew/opt/openssl@3/lib/libssl.3.dylib' (no such file), '/Users/dev/.rustup/toolchains/esp/lib/libssl.3.dylib' (no such file), '/Users/dev/lib/libssl.3.dylib' (no such file), '/usr/local/lib/libssl.3.dylib' (no such file), '/usr/lib/libssl.3.dylib' (no such file)
zsh: abort      cargo check
```

**Comment by georgik** [comment]
Thank you @lynaghk for spotting the problem. I guess it was caused by manual build of aarch64 for macOS. I re-run the build again. The artifact should become available in 30 minutes.

**Comment by georgik** [comment]
The artifact is ready. The problem should not occur.

**Comment by lynaghk** [comment]
Just tried it out, everything working as intended. Thanks for your hard work on this project, it's really great to be able to use Rust on ESP32 =D

**Comment by georgik** [comment]
👍  Thank you very much for the confirmation and encouraging words @lynaghk.

**Pull request merged**
